export const GET_ACCOUNTS_LOAD = "GET_ACCOUNTS_LOAD";
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";
export const GET_ACCOUNTS_FAIL = "GET_ACCOUNTS_FAIL";
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const SIGNUP_AGENT_SUCCESS = "SIGNUP_AGENT_SUCCESS";
export const GET_ALL_AGENT_SUCCESS = "GET_ALL_AGENT_SUCCESS";
export const GET_UNVERIF_SUCCESS = "GET_UNVERIF_SUCCESS";
